name: Deploy-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  setup-webserver:
    name: Install apache2
    runs-on: ubuntu-latest
    
    steps:
      - name: install apache2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_SSH_KEY }}
          port: 22
          script: |
            apt update
            apt install apache2 -y

  
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    needs: setup-webserver
  
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main

        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_FOLDER }}

      
